/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAiInsightsRouteImport } from './routes/_shell/ai-insights'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell/analytics'
import { Route as ShellContractsRouteImport } from './routes/_shell/contracts'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell/integrations'
import { Route as ShellInvoicesRouteImport } from './routes/_shell/invoices'
import { Route as ShellLeaksRouteImport } from './routes/_shell/leaks'
import { Route as ShellNotificationsRouteImport } from './routes/_shell/notifications'
import { Route as ShellPaymentsRouteImport } from './routes/_shell/payments'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellRecoveryRouteImport } from './routes/_shell/recovery'
import { Route as ShellReportsRouteImport } from './routes/_shell/reports'
import { Route as ShellRolesRouteImport } from './routes/_shell/roles'
import { Route as ShellSecurityRouteImport } from './routes/_shell/security'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellTransactionsRouteImport } from './routes/_shell/transactions'
import { Route as ShellUsersRouteImport } from './routes/_shell/users'
import { Route as ShellVendorsRouteImport } from './routes/_shell/vendors'
import { Route as ApiPublicErpCallbackRouteImport } from './routes/api/public/erp/callback'
import { Route as ApiPublicErpIngestRouteImport } from './routes/api/public/erp/ingest'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiInsightsRoute = ShellAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellContractsRoute = ShellContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvoicesRoute = ShellInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeaksRoute = ShellLeaksRouteImport.update({
  id: '/leaks',
  path: '/leaks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaymentsRoute = ShellPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecoveryRoute = ShellRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRolesRoute = ShellRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSecurityRoute = ShellSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVendorsRoute = ShellVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicErpCallbackRoute = ApiPublicErpCallbackRouteImport.update({
  id: '/api/public/erp/callback',
  path: '/api/public/erp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErpIngestRoute = ApiPublicErpIngestRouteImport.update({
  id: '/api/public/erp/ingest',
  path: '/api/public/erp/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-insights': typeof ShellAiInsightsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/contracts': typeof ShellContractsRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/invoices': typeof ShellInvoicesRoute
  '/leaks': typeof ShellLeaksRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/profile': typeof ShellProfileRoute
  '/recovery': typeof ShellRecoveryRoute
  '/reports': typeof ShellReportsRoute
  '/roles': typeof ShellRolesRoute
  '/security': typeof ShellSecurityRoute
  '/settings': typeof ShellSettingsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/users': typeof ShellUsersRoute
  '/vendors': typeof ShellVendorsRoute
  '/api/public/erp/callback': typeof ApiPublicErpCallbackRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRoutesByTo {
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/ai-insights': typeof ShellAiInsightsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/contracts': typeof ShellContractsRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/invoices': typeof ShellInvoicesRoute
  '/leaks': typeof ShellLeaksRoute
  '/notifications': typeof ShellNotificationsRoute
  '/payments': typeof ShellPaymentsRoute
  '/profile': typeof ShellProfileRoute
  '/recovery': typeof ShellRecoveryRoute
  '/reports': typeof ShellReportsRoute
  '/roles': typeof ShellRolesRoute
  '/security': typeof ShellSecurityRoute
  '/settings': typeof ShellSettingsRoute
  '/transactions': typeof ShellTransactionsRoute
  '/users': typeof ShellUsersRoute
  '/vendors': typeof ShellVendorsRoute
  '/': typeof ShellIndexRoute
  '/api/public/erp/callback': typeof ApiPublicErpCallbackRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_shell/ai-insights': typeof ShellAiInsightsRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/contracts': typeof ShellContractsRoute
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/invoices': typeof ShellInvoicesRoute
  '/_shell/leaks': typeof ShellLeaksRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/payments': typeof ShellPaymentsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/recovery': typeof ShellRecoveryRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/roles': typeof ShellRolesRoute
  '/_shell/security': typeof ShellSecurityRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/vendors': typeof ShellVendorsRoute
  '/_shell/': typeof ShellIndexRoute
  '/api/public/erp/callback': typeof ApiPublicErpCallbackRoute
  '/api/public/erp/ingest': typeof ApiPublicErpIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/ai-insights'
    | '/analytics'
    | '/contracts'
    | '/integrations'
    | '/invoices'
    | '/leaks'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/recovery'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/users'
    | '/vendors'
    | '/api/public/erp/callback'
    | '/api/public/erp/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cookie-policy'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/ai-insights'
    | '/analytics'
    | '/contracts'
    | '/integrations'
    | '/invoices'
    | '/leaks'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/recovery'
    | '/reports'
    | '/roles'
    | '/security'
    | '/settings'
    | '/transactions'
    | '/users'
    | '/vendors'
    | '/'
    | '/api/public/erp/callback'
    | '/api/public/erp/ingest'
  id:
    | '__root__'
    | '/_shell'
    | '/cookie-policy'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/terms-and-conditions'
    | '/verify-email'
    | '/_shell/ai-insights'
    | '/_shell/analytics'
    | '/_shell/contracts'
    | '/_shell/integrations'
    | '/_shell/invoices'
    | '/_shell/leaks'
    | '/_shell/notifications'
    | '/_shell/payments'
    | '/_shell/profile'
    | '/_shell/recovery'
    | '/_shell/reports'
    | '/_shell/roles'
    | '/_shell/security'
    | '/_shell/settings'
    | '/_shell/transactions'
    | '/_shell/users'
    | '/_shell/vendors'
    | '/_shell/'
    | '/api/public/erp/callback'
    | '/api/public/erp/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiPublicErpCallbackRoute: typeof ApiPublicErpCallbackRoute
  ApiPublicErpIngestRoute: typeof ApiPublicErpIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai-insights': {
      id: '/_shell/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof ShellAiInsightsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/contracts': {
      id: '/_shell/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ShellContractsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/invoices': {
      id: '/_shell/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ShellInvoicesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leaks': {
      id: '/_shell/leaks'
      path: '/leaks'
      fullPath: '/leaks'
      preLoaderRoute: typeof ShellLeaksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/payments': {
      id: '/_shell/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof ShellPaymentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recovery': {
      id: '/_shell/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof ShellRecoveryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/roles': {
      id: '/_shell/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ShellRolesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/security': {
      id: '/_shell/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ShellSecurityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vendors': {
      id: '/_shell/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof ShellVendorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/erp/callback': {
      id: '/api/public/erp/callback'
      path: '/api/public/erp/callback'
      fullPath: '/api/public/erp/callback'
      preLoaderRoute: typeof ApiPublicErpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/erp/ingest': {
      id: '/api/public/erp/ingest'
      path: '/api/public/erp/ingest'
      fullPath: '/api/public/erp/ingest'
      preLoaderRoute: typeof ApiPublicErpIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellAiInsightsRoute: typeof ShellAiInsightsRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellContractsRoute: typeof ShellContractsRoute
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellInvoicesRoute: typeof ShellInvoicesRoute
  ShellLeaksRoute: typeof ShellLeaksRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPaymentsRoute: typeof ShellPaymentsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellRecoveryRoute: typeof ShellRecoveryRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellRolesRoute: typeof ShellRolesRoute
  ShellSecurityRoute: typeof ShellSecurityRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellVendorsRoute: typeof ShellVendorsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiInsightsRoute: ShellAiInsightsRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellContractsRoute: ShellContractsRoute,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellInvoicesRoute: ShellInvoicesRoute,
  ShellLeaksRoute: ShellLeaksRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPaymentsRoute: ShellPaymentsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellRecoveryRoute: ShellRecoveryRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellRolesRoute: ShellRolesRoute,
  ShellSecurityRoute: ShellSecurityRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellVendorsRoute: ShellVendorsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiPublicErpCallbackRoute: ApiPublicErpCallbackRoute,
  ApiPublicErpIngestRoute: ApiPublicErpIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
